### ISSUE TITLE
大佬厉害！！感谢。 用 爱啪思道 下载安装的app无法注入

### ISSUE THREAD

**Issue by lzy0699** [Lessica/TrollFools#11]
用 爱啪思道 下载安装的app无法注入，找不到关联的框架。不管是直接安装还airdrop方式安装，直接从商店安装的就没问题，测试的是芒果TV美区版。不知道这种问题能否解决😂

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Lessica** [comment]
我想可以找厂长看下

**Comment by Lessica** [comment]
厂长说了，爱啪思道下载安装的 App 的所有的 Framework 都带壳，不在支持范围内。
