### ISSUE TITLE
错误代码

### ISSUE THREAD

**Issue by zhouzhiqiang10063** [Lessica/TrollFools#12]
错误代码:65280

**Comment by Lessica** [comment]
卸载重装试下 1.3-9

**Comment by zhouzhiqiang10063** [comment]
试过了跟多次，也更新到最新版，不行，ct_bypass 意外退出，错误代码
65280

**Comment by Lessica** [comment]
插件问题，换一个

**Comment by zhouzhiqiang10063** [comment]
😅好的老大

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月20日 23:12 |
| 收件人 | Lessica/TrollFools ***@***.***> |
| 抄送人 | zhouzhiqiang10063 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Lessica/TrollFools] 错误代码 (Issue #12) |

插件问题，换一个
