### ISSUE TITLE
网易云注入，错误代码256

### ISSUE THREAD

**Issue by ChenDY2233** [Lessica/TrollFools#13]
系统版本：16.6.1
TrollFools：1.3-9
网易云版本：9.1.23

注入：[网易云增强1.1.0.dylib](https://wwm.lanzoue.com/iHRwh253gifa)

![image](https://github.com/user-attachments/assets/04cae05e-d7ae-4c1e-824e-ac812647a0ae)

**Comment by Lessica** [comment]
插件本身有不支持的 Load Command，可能是有保护之类的，换一个。
