### ISSUE TITLE
此app安装后无法在trollfools里看到

### ISSUE THREAD

**Issue by cnrest** [Lessica/TrollFools#16]
应用安装后不显示app名字，只有bid
[https://apps.apple.com/cn/app/widgy-widgets-home-lock-watch/id1524540481](url)
![IMG_3194](https://github.com/user-attachments/assets/7ee61b71-905a-4e31-ad0e-9378fb0afc04)
![IMG_3195](https://github.com/user-attachments/assets/37b40675-3f72-4438-8d24-54fe558fca19)
![IMG_3196](https://github.com/user-attachments/assets/8b1e92f0-29a2-49f1-af7c-0b0359f35c9d)

**Comment by cnrest** [comment]
应用列表上下滑动也看了好多遍，均未看到这个app

**Comment by Lessica** [comment]
看到这几个字了没：「可注入的应用程序」
