### ISSUE TITLE
注入进去没有任何反应

### ISSUE THREAD

**Issue by hedada-hc** [Lessica/TrollFools#17]
我注入抖音，注入进去后没有任何反应，原版我是theos项目 tweak.x 编译为deb后缀文件了，然后我从里面提取到了 .dylib 文件，然后用这个软件注入，进去后没有任何反应，因为只要注入进去后会有一个弹窗，我在越狱环境上面 安装deb 正常弹出弹窗，但是通过这样软件注入就没有任何反应是因为 theos项目Mackfile 编写的问题吗？我用的是默认的
这是我的 Makefiles，会有无根目录和有根目录的问题吗？我的系统是15.6 没有越狱安装的巨魔
TARGET := iphone:clang:latest:7.0
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = dy

dy_FILES = Tweak.x
dy_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk

**Comment by Lessica** [comment]
自己研究
