### ISSUE TITLE
15.1系统13PM手机使用1.3（9）版本注入抖音失败报错9

### ISSUE THREAD

**Issue by dhdhd222** [Lessica/TrollFools#18]
15.1系统13PM手机使用1.3（9）版本注入抖音失败报错9

**Comment by BI3NWQ** [comment]
15.2最新1.3-9注入提示错误代码9
巨魔1.1.5提示错误代码-1升级巨魔最新2.0.15就变成错误代码9了
![CFEB10A8-BF2C-4095-995B-BCDD56B64393](https://github.com/user-attachments/assets/9ec5bc94-4dcd-430f-9235-3473c2a9e6bd)
![621EE4EF-1CD0-4E7B-B1BB-EFA419978D20](https://github.com/user-attachments/assets/e9120b7d-def9-4d62-942e-41d65855bd41)
![8772CD85-6F55-4223-9FE2-B0F31A92126E](https://github.com/user-attachments/assets/bcaf76f4-05fd-4624-80f5-8729db093eaa)

**Comment by Lessica** [comment]
非工具问题
