### ISSUE TITLE
点击全部推出后，后续选择插入动画效果延迟

### ISSUE THREAD

**Issue by jackeyxiang** [Lessica/TrollFools#19]
尝试 app：Spotify
步骤：点击注入插件两个，app闪退，点击全部推出，动画延迟几秒，之后动画效果有些延迟，偶现插入插件，选择插件没有打开按钮，只有取消和全选
细节如图，第一张是官替包，第二张是注入插件后砸壳包，第三张是闪退插件，猜测是否是依赖不全，同理twitter 也是这样的情况
感谢大佬辛苦开发🙏

![93DE0389-1B4F-4651-817A-DEDD94656525](https://github.com/user-attachments/assets/a1c481ac-697b-40d5-b07f-06fec4ea8151)

![C949EEBB-6AC7-4FAB-BD8A-2FF7B9443F59](https://github.com/user-attachments/assets/38f00e8b-db57-4c86-b3b2-5928d6af58df)

![59CA9CCE-BDF9-40A2-B6C4-C71874AE1FA1](https://github.com/user-attachments/assets/c9f2069d-d784-4b41-adad-d1bca88f15b7)

**Comment by Lessica** [comment]
非工具问题
