### ISSUE TITLE
注入报错

### ISSUE THREAD

**Issue by 459339321** [Lessica/TrollFools#21]
手机iphone12，版本14.2.1，巨魔安装之后注入dylib报错，用的是14版本的包，报错如下
![1](https://github.com/user-attachments/assets/555d3364-b90a-489e-9bfa-e17a8a712e96)
题外话：之前大虾，虫子他们那个QQ群是多少来着。换Q了找不到了，12年那会儿还在群里玩呢

**Comment by BI3NWQ** [comment]
![C17251B3-C68F-4BBE-A935-6ED7EB9EA039](https://github.com/user-attachments/assets/e035ebd3-76f7-4022-9934-37fe49217a30)
![F4CC8683-31A9-47B3-85E4-FEC6D5CC8B11](https://github.com/user-attachments/assets/85ac24ef-fcc9-4bbc-8b0e-e48d0f51e31c)
![240AB54E-FC7D-4567-B45A-273A64A36674](https://github.com/user-attachments/assets/165d42de-6817-4839-99e7-8de2c81cd076)

**Comment by Lessica** [comment]
暂不支持 iOS 14
