### ISSUE TITLE
微信8.0.33注入失败求修复

### ISSUE THREAD

**Issue by PaTTeeL** [Lessica/TrollFools#22]
微信 8.0.33 注入提示错误：没有找到符合条件的框架。
两台手机都能复现： iOS 15.4.1 @ iPhone 8 Plus 和 iOS 14.8 @ iPhone XR，用的是TrollFools 1.3-9。
升级到 8.0.45 就注入成功了，8.0.33是最后一个无需后台常驻支持callkit的版本了，求修复。

另：iOS 14.8 下可以成功注入 libJailedShim.dylib (122KB)，但注入 WCPureExtension.dylib (16.2MB) 会提示 llvm-install-name-tool 意外退出，错误代码 6，感觉可能是文件过大的原因？实测554KB的dylib注入成功，1.89MB的dylib会提示llvm-install-name-tool错误6。

**Comment by Lessica** [comment]
此类问题咨询插件开发者，请勿提 Issue。

**Comment by PaTTeeL** [comment]
> 此类问题咨询插件开发者，请勿提 Issue。

这两个插件在8.0.33下用另一个工具InjectWeChat_1.1-2.tipa是可以正常注入并使用的，只是用TrollFools注入失败了，提issue只是希望找一个的通用工具而不想为每个app专门装一个注入器……

**Comment by Lessica** [comment]
做这个工具不是为了满足你的需求的，请遵守社区规范
