### ISSUE TITLE
笨蛋操作导致无法下载官方微信

### ISSUE THREAD

**Issue by Myth0212** [Lessica/TrollFools#25]
在覆盖商店微信之前，往巨魔微信注入插件后，打开巨魔微信闪退 遂删掉插件，再去商店覆盖微信会无限覆盖失败。目前还是之前的巨魔微信，现在我删掉巨魔微信，重新下载商店微信，下载安装后微信图标左边有下载标志，点开就显示无法安装微信， 目前不知道怎么解决。试过filza删文件安装，操作貌似没问题但失败。试了试别的软件这样操作没有问题 就只有微信不能覆盖安装 删除安装也不行 求大佬指点

**Comment by Lessica** [comment]
去其他地方问，别在这问，这里不是给你问这类问题的地方。
