### ISSUE TITLE
怎么有些app显示不出来呢？比如说皮皮虾

### ISSUE THREAD

**Issue by saltwest** [Lessica/TrollFools#27]
普通用户请勿提交「插件无效」、「闪退」，「错误代码」等问题，请找插件开发者适配。  
插件开发者反馈问题请先自行排查原因，**不要上来就丢源代码**。描述问题时请详细且有条理地描述问题，不要语无伦次。

**Comment by asd549771282** [comment]
一样想注入皮皮虾，但列表一直没有

**Comment by saltwest** [comment]
YouTobe music也没有

**Comment by Lessica** [comment]
不显示就是不支持，不要问为什么不支持，技术原因。
