### ISSUE TITLE
关于 TFs App 升级的方式建议、

### ISSUE THREAD

**Issue by CicAway** [Lessica/TrollFools#29]
82 大神、咱们这个软件升级方式是否能设置成如巨魔一样的内置升级方式？每次升级都要来 GHb 下载、再安装、😂感觉没有内置提示升级然后点击一下就自动升级的方便…可以加入这个嘛？不太懂问问您。

**Comment by Look-UI** [comment]
能否继续支持巨魔应用呢！砸壳安装的应用需要支持

**Comment by oddhw** [comment]
> 能否继续支持巨魔应用呢！砸壳安装的应用需要支持

不是，你都已经砸壳巨魔了，还有必要用这个了么

**Comment by Look-UI** [comment]
> > 能否继续支持巨魔应用呢！砸壳安装的应用需要支持
> 
> 不是，你都已经砸壳巨魔了，还有必要用这个了么

目前有一个可以调整的小细节，就是任务图标和桌面图标不一致

**Comment by 3zang** [comment]
内置一个目录,用来放/导入deb/dylib文件 ,还有 自己通过抓包工具抓的自己id下载的软件 为啥注入没效果呢,虽然已经说明了,但是能不能加上

**Comment by songxing10000** [comment]
ios15.8.2 ios16.5 注入dylib没有效果

**Comment by Lessica** [comment]
不是经常更新，没必要。
