### ISSUE TITLE
No eligible framework found.

### ISSUE THREAD

**Issue by piscesCat** [Lessica/TrollFools#38]
Bundle id: com.garena.game.kgtw/kgvn
App name: AOV/Honor of King
please fix it.

**Comment by Lessica** [comment]
The limitations are clearly declared at the main page.

**Comment by piscesCat** [comment]
> The limitations are clearly declared at the main page.

not a restriction, just lets override this with a binary that added the correct path to dylib, it will run (tested)
![IMG_6825](https://github.com/user-attachments/assets/6e255ab6-42d2-409a-aa59-8778a6b25556)
