### ISSUE TITLE
注入巨魔应用失败

### ISSUE THREAD

**Issue by LaoYuan77** [Lessica/TrollFools#44]
我是12PM的14.3系统，巨魔一代1.5.1版本，试了几个插件注入巨魔应用失败
![QQ图片20240725082256](https://github.com/user-attachments/assets/1b12303f-c1f7-4908-a92d-435c23d2f392)

**Comment by mumuisdog** [comment]
這工具是注入原生AppStore下載的App

**Comment by anwen-anyi** [comment]
> 這工具是注入原生AppStore下載的App

🥲不是已经支持注入巨魔了吗? 而且软件里面也显示巨魔应用了

**Comment by Lessica** [comment]
巨魔应用都是别人魔改过的，失败就别反馈了，已经被糟蹋过的还得我负责？

**Comment by LaoYuan77** [comment]
那干嘛要写支持注入巨魔应用呢？又何必在软件显示巨魔应用

i_82 ***@***.***> 于2024年7月26日周五 23:05写道：
