### ISSUE TITLE
Can You Fix Inject Dylib My game Arena Of valor?

### ISSUE THREAD

**Issue by trungtoan337** [Lessica/TrollFools#56]
i make mod menu dylib for non jailbreak and try inject it but it error No eligible framework not found.
![D9827682-1CC7-43CE-8821-FF5EAF68F682](https://github.com/user-attachments/assets/4b2d8263-66f3-4e38-aab2-6d2d138c9fb4)

**Comment by Lessica** [comment]
There are billions of apps over the world. Why I need to fix them for you?

**Comment by Lessica** [comment]
> ## Limitations
> 
> - [x] Removable system applications
> - [x] Decrypted App Store applications (TrollStore applications)
> - [x] Encrypted App Store applications with bare dynamic library

See **Limitations**
