### ISSUE TITLE
can not inject in all app

### ISSUE THREAD

**Issue by votanthanh333** [Lessica/TrollFools#64]
error ct bypass terminated with signal 0, it occurs with all app, error form TrollFools, hope u fix this soon, ip xsmax ios 15.2.1
![620B88F4-A109-4AA7-B56B-5AD65CDD7CE7](https://github.com/user-attachments/assets/f77288a7-e825-4431-ae04-78e7ad42f4ab)

**Comment by Lessica** [comment]
Never said it supports all app. ???

**Comment by votanthanh333** [comment]
> Never said it supports all app. ???
I mean TrollFools having error, i can not inject any app, like Youtube or tiktok, it is error

**Comment by votanthanh333** [comment]
sorry because of unclear issue. Because im not good at english

**Comment by Lessica** [comment]
Ok. Duplicate of #60

**Comment by votanthanh333** [comment]
> Ok. Duplicate of #60

That’s right, hope u fix this soon 😭
