### ISSUE TITLE
I can’t select .deb file

### ISSUE THREAD

**Issue by HJRaptor** [Lessica/TrollFools#68]
I can’t select .deb in file picker. It is greyed out. ![E2B607C4-A259-4CD1-B8C9-706937E45616](https://github.com/user-attachments/assets/d6db1232-4f3d-4cbb-b048-8c64f6aa543c)

**Comment by zouyelin** [comment]
高德地图插件在2.66注入闪退，2.52正常

**Comment by HJRaptor** [comment]
It is still greyed out on 2.5.2

**Comment by Lessica** [comment]
TrollFools does not support `.Deb` files. Make sure you are using the official version.
